version: '2.4'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_BROKERS}
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka-producer:
    image: joshfoeh/kafka-producer
    container_name: kafka-producer
    ports:
      - "${KAFKA_PRODUCER_SERVER_PORT}:${KAFKA_PRODUCER_SERVER_PORT}"
    environment:
      DEFAULT_TOPIC: ${DEFAULT_TOPIC}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      SERVER_PORT: ${KAFKA_PRODUCER_SERVER_PORT}
    depends_on:
      - kafka